services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PLANILHA ACOMPANHAMENTO ORÇAMENTÁRIO
    ports:
      - '3104:3104'
    networks:
      - reverse_proxy_net
      - monitoring_net
    volumes:
      - /mnt/TCE:/mnt/TCE
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

networks:
  reverse_proxy_net:
    external: true
  monitoring_net:
    external: true
