[server]
port = 3103
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[theme]
base = "light"  # ou "dark"
primaryColor = "#4B8BBE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[client]
toolbarMode = "minimal"